config/routes.rb
Rails.application.routes.draw do

  get 'settings/index'

  get 'settings/update'

  get 'view_orders/index'

  get '/en/home_index_path' => 'home#index'
  
  get '/en/cart_path' => 'carts#show'

  get '/en/product/category/:id', to: 'products#category', as: 'category' 

  get '/en/carts/:id/cupon_path', to: 'carts#cupon_apply', as: 'cupon'
  
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  scope '(:locale)' do
    resources :settings, only: [:index, :create, :destroy]
    resource :settings, only: [:edit] do
      collection do
        patch 'update_password'
      end
    end
    resources :home, only: [:index, :create]
    resources :books, only: [:show, :update]
    resources :orders, only: [:index, :create]
    resources :line_items, only: [:index, :new, :create, :update, :destroy]
    resources :carts, only: [:show, :edit]
    resources :payment, only: [:index, :create]
    resources :confirm, only: [:index]
    resources :complete, only: [:index]
    resources :delivery, only: [:index, :create]
    resources :view_orders, only: [:index]
    resource :product do
      resources :comments
    end

    root 'home#index', as: 'store', via: :all
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  include SettingsHelper

  before_action :authenticate_user!
  before_action :set_user, only: [:index, :update, :update_password]

  def update
    @user.update_attributes(user_params)
    redirect_to settings_index_path
  end

  def update_password
    if @user.update_with_password(user_params)
      bypass_sign_in(@user)
      redirect_to root_path
    else
      render "index"
    end
  end

  def destroy 
    resource.soft_delete
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)  
    set_flash_message :notice, :destroyed if is_flashing_format?  
    yield resource if block_given?  
    respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }  
  end  

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:password, :password_confirmation, :current_password, :email, :first_name, :last_name, :address, :city, :zip, :country, :phone, :shipping_first_name, :shipping_last_name, :shipping_address, :shipping_city, :shipping_zip, :shipping_country, :shipping_phone)
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/settings/_form.html.haml
.hidden-xs.hidden-sm
  .row
    .col-md-5
      %h3.general-subtitle= t('.billing_address')
    .col-md-5.col-md-offset-1
      %h3.general-subtitle= t('.shipping_address')
.row
  .col-md-5.mb-40
    .visible-xs.visible-sm
      %h3.general-subtitle= t('.billing_address')
    = form_for current_user, :url => settings_update_path, :method => :get do |f|
      .form-group
        = f.label :first_name, t('.first_name'), { class: 'control-label font-weight-lights', for: "first_name" }
        = f.text_field :first_name, { class: 'form-control', id: 'firstName', type: "text", placeholder: "First Name" }
      .form-group
        = f.label :last_name, t('.last_name'), { class: 'control-label font-weight-lights', for: "last_name" }
        = f.text_field :last_name, { class: 'form-control', id: 'lastName', type: "text", placeholder: "Last Name" }
      .form-group
        = f.label :address, t('.address'), { class: 'control-label font-weight-lights', for: "address" }
        = f.text_field :address, { class: 'form-control', id: 'address', type: "text", placeholder: "Address" }
      .form-group
        = f.label :city, t('.city'), { class: 'control-label font-weight-lights', for: "city" }
        = f.text_field :city, { class: 'form-control', id: 'city', type: "text", placeholder: "City" }
      .form-group
        = f.label :zip, t('.zip'), { class: 'control-label font-weight-lights', for: "zip" }
        = f.text_field :zip, { class: 'form-control', id: 'zip', type: "text", placeholder: "Zip" }
      .form-group
        = f.label :country, t('.country'), { class: 'control-label font-weight-lights', for: "country" }
        = f.text_field :country, { class: 'form-control', id: 'country', type: "text", placeholder: "Country" }
      .form-group
        = f.label :phone, t('.phone'), { class: 'control-label font-weight-lights', for: "phone" }
        = f.text_field :phone, { class: 'form-control', id: 'phone', type: "tel", placeholder: "Example +355 66 123 4567" }
      .text-center
        = f.submit 'Save', {class: 'btn center-block mb-20'}
  .col-md-5.col-md-offset-1.mb-60
    .visible-xs.visible-sm
      %h3.general-subtitle Shipping Address
    = form_for current_user, :url => settings_update_path, :method => :get do |f|
      .form-group
        = f.label :shipping_first_name, t('.first_name'), { class: 'control-label font-weight-lights', for: "shipping_first_name" }
        = f.text_field :shipping_first_name, { class: 'form-control', id: 'firstName', type: "text", placeholder: "First Name" }
      .form-group
        = f.label :shipping_last_name, t('.last_name'), { class: 'control-label font-weight-lights', for: "shipping_last_name" }
        = f.text_field :shipping_last_name, { class: 'form-control', id: 'lastName', type: "text", placeholder: "Last Name" }
      .form-group
        = f.label :shipping_address, t('.address'), { class: 'control-label font-weight-lights', for: "shipping_address" }
        = f.text_field :shipping_address, { class: 'form-control', id: 'address', type: "text", placeholder: "Address" }
      .form-group
        = f.label :shipping_city, t('.city'), { class: 'control-label font-weight-lights', for: "shipping_city" }
        = f.text_field :shipping_city, { class: 'form-control', id: 'city', type: "text", placeholder: "City" }
      .form-group
        = f.label :shipping_zip, t('.zip'), { class: 'control-label font-weight-lights', for: "shipping_zip" }
        = f.text_field :shipping_zip, { class: 'form-control', id: 'zip', type: "text", placeholder: "Zip" }
      .form-group
        = f.label :shipping_country, t('.country'), { class: 'control-label font-weight-lights', for: "shipping_country" }
        = f.text_field :shipping_country, { class: 'form-control', id: 'country', type: "text", placeholder: "Country" }
      .form-group
        = f.label :shipping_phone, t('.phone'), { class: 'control-label font-weight-lights', for: "shipping_phone" }
        = f.text_field :shipping_phone, { class: 'form-control', id: 'phone', type: "tel", placeholder: "Example +355 66 123 4567" }
      .text-center
        = f.submit 'Save', {class: 'btn center-block mb-20'}

app/views/settings/_form_settings.html.haml
.row.mb-60
  .col-sm-5
    %p.in-gold-500.font-18.mb-25 Email
    .general-text-align
    = form_for( current_user, :url => settings_update_path, :method => :get, html: { :class => 'general-form-md'} ) do |f|
      .form-group.mb-35
        = f.label :email, 'Enter Email', { class: 'control-label font-weight-lights', for: "email" }
        = f.text_field :email, { class: 'form-control', id: 'email', type: "email", placeholder: "Enter your email" }
      .general-text-align
        = f.submit 'Save', {class: 'btn btn-default mb-35'}
  .col-sm-5.col-sm-offset-1
    %p.in-gold-500.font-18.mb-25 Password
    = form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :put, class: "general-form" }) do |f|
      = devise_error_messages!
      = f.hidden_field :reset_password_token
      .form-group.mb-30
        %label.control-label.font-weight-light{for: "password"} Type a new Password
        = f.password_field :password, autofocus: true, autocomplete: "off", placeholder: "Type a new Password", id: "password", class: "form-control"
      .form-group.mb-40
        %label.control-label.font-weight-light{for: "confirmPassword"} Confirm Password
        = f.password_field :password_confirmation, autocomplete: "off", placeholder: "Confirm Password", id: "confirmPassword", class: "form-control"
      .actions
        = f.submit "Change", class: "btn btn-default center-block mb-20"
  .col-sm-12
    .divider-lg-bottom
    %p.in-gold-500.font-18.mb-25.pt-20 Remove Account
    %form
      .general-settings-btn
        = button_to 'Please Remove My Account', setting_path(:user), method: "delete", class: "btn mb-20"
      .form-group.checkbox.general-settings-checkbox
        %label.font-weight-light.pl-0
          %input.checkbox-input{type: "checkbox", hidden: "true"}
          %span.checkbox-icon
            %i.fa.fa-check
          %span.checkbox-text I understand that all data will be lost
          

app/views/settings/index.html.haml
%h1.general-title-margin Settings
%ul.nav.nav-tabs.mb-20{role: "tablist"}
  %li.mb-10.active{role: "presentation"}
    %a{href: "#address", 'aria-controls': "address", role: "tab", 'data-toggle': "tab"} Address
  %li.mb-10{role: "presentation"}
    %a{href: "#privacy", 'aria-controls': "privacy", role: "tab", 'data-toggle': "tab"} Privacy
.tab-content
  #address.tab-pane.fade.in.active.general-main-wrap{role: "tabpanel"}
    = render 'form'
  #privacy.tab-pane.fade{role: "tabpanel"}
    = render 'form_settings'