config/routes.rb
Rails.application.routes.draw do

  get 'settings/index'

  get 'settings/update'

  get 'view_orders/index'

  get '/en/home_index_path' => 'home#index'
  
  get '/en/cart_path' => 'carts#show'

  get '/en/product/category/:id', to: 'products#category', as: 'category' 

  get '/en/carts/:id/cupon_path', to: 'carts#cupon_apply', as: 'cupon'
  
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  scope '(:locale)' do
    resources :settings, only: [:index, :create, :destroy]
    resource :settings, only: [:edit] do
      collection do
        patch 'update_password'
      end
    end
    resources :home, only: [:index, :create]
    resources :books, only: [:show, :update]
    resources :orders, only: [:index, :create]
    resources :line_items, only: [:index, :new, :create, :update, :destroy]
    resources :carts, only: [:show, :edit]
    resources :payment, only: [:index, :create]
    resources :confirm, only: [:index]
    resources :complete, only: [:index]
    resources :delivery, only: [:index, :create]
    resources :view_orders, only: [:index]
    resource :product do
      resources :comments
    end

    root 'home#index', as: 'store', via: :all
  end
end

app/controllers/confirm_controller.rb
class ConfirmController < ApplicationController
  include CurrentCart

  before_action :authenticate_user!
  before_action :set_cart, only: [:index]

  def index
    session[:return_to] = true
    @order = Order.find(session[:order_id])
    @delivery = Delivery.find(@order.delivery_id)
    render 'confirm/index'
  end
end

app/helpers/confirm_helper.rb
module ConfirmHelper
end

app/views/confirm/index.html.haml
%h1.general-title-margin Checkout
%ul.steps.list-inline
  %li.step.active
    %span.step-number
      %i.fa.fa-check.step-icon
    %span.step-text.hidden-xs Address
  %li.step-divider
  %li.step.active
    %span.step-number
      %i.fa.fa-check.step-icon
    %span.step-text.hidden-xs Delivery
  %li.step-divider
  %li.step.active
    %span.step-number
      %i.fa.fa-check.step-icon
    %span.step-text.hidden-xs Payment
  %li.step-divider
  %li.step.active
    %span.step-number 4
    %span.step-text.hidden-xs Confirm
  %li.step-divider
  %li.step
    %span.step-number 5
    %span.step-text.hidden-xs Complete
.row.mb-20
  .col-sm-3
    %h3.general-subtitle Shipping Address
    %p.general-address
      = "#{current_user.shipping_first_name} #{current_user.shipping_last_name}"
      %span.general-edit= link_to "edit", orders_path, method: :get, class: 'general-edit' 
      %br
      = current_user.shipping_address
      %br
      = "#{current_user.shipping_city} #{current_user.shipping_zip}"
      %br
      = current_user.shipping_country
      %br
      = "Phone #{current_user.shipping_phone}"
  .col-sm-3
    %h3.general-subtitle Billing Address
    %p.general-address
      = "#{current_user.first_name} #{current_user.last_name}"
      %span.general-edit= link_to "edit", orders_path, method: :get, class: 'general-edit' 
      %br
      = current_user.address
      %br
      = "#{current_user.city} #{current_user.zip}"
      %br
      = current_user.country
      %br
      = "Phone #{current_user.phone}"
  .col-sm-3
    %h3.general-subtitle Shipments
    %p.general-address
      = "Delivery #{@delivery.days} Days"
      %span.general-edit= link_to "edit", delivery_index_path, method: :get, class: 'general-edit' 
      %br
      = @delivery.method
  .col-sm-3
    %h3.general-subtitle Payment Information
    %p.general-address
      = @order.card_number
      %span.general-edit= link_to "edit", payment_index_path, method: :get, class: 'general-edit' 
      %br
      = @order.mm_yy
.hidden-xs.divider-lg.pt-20
  %table.table.table-hover
    %thead
      %tr
        %th
          %span.in-grey-600 Book
        %th.col-method
        %th
          %span.in-grey-600 Price
        %th
          %span.in-grey-600 Quantity
        %th
          %span.in-grey-600 Total
    - @cart.line_items.each do |item|
      %tbody
        %tr
          %td
            .general-img-wrap-table
              %img.cart-img-shadow.pull-left.width-full{src: item.product.image_url}
          %td
            %p.general-title= item.product.title
            %p.in-grey-600.font-weight-light= item.product.title
          %td
            %span.font-16.in-gold-500= "€#{item.product.price}"
          %td
            %span.ml-30= item.quantity
          %td
            %span.font-16.in-gold-500= number_to_currency(item.total_price)
.text-center.general-text-right
  %p.in-gold-500.font-18 Order Summary
  %table.general-summary-table.general-summary-table-right.general-text-right
    %tr
      %td
        %p.font-16 Subtotal:
      %td
        %p.font-16= number_to_currency(@cart.total_price + @order.total_delivery)
    %tr
      %td
        %p.font-16 Coupon:
      %td
        %p.font-16= number_to_currency(@order.total_cupon)
    %tr
      %td
        %strong.font-18 Order Total:
      %td
        %strong.font-18= number_to_currency(@cart.total_price + @order.total_delivery - @order.total_cupon)
.text-center
  = button_to "Place Order", complete_index_path, method: :get, class: 'btn btn-default mb-20'

app/views/confirm/new.html.haml
%h1.general-title-margin Checkout
%ul.steps.list-inline
  %li.step.active
    %span.step-number
      %i.fa.fa-check.step-icon
    %span.step-text.hidden-xs Address
  %li.step-divider
  %li.step.active
    %span.step-number
      %i.fa.fa-check.step-icon
    %span.step-text.hidden-xs Delivery
  %li.step-divider
  %li.step.active
    %span.step-number
      %i.fa.fa-check.step-icon
    %span.step-text.hidden-xs Payment
  %li.step-divider
  %li.step.active
    %span.step-number 4
    %span.step-text.hidden-xs Confirm
  %li.step-divider
  %li.step
    %span.step-number 5
    %span.step-text.hidden-xs Complete
.row.mb-20
  .col-sm-3
    %h3.general-subtitle Shipping Address
    %p.general-address
      John Doe
      %span.general-edit edit
      %br
      44 Fifth Ave v231
      %br
      New York NY 1001
      %br
      United States
      %br
      Phone +16507599755
  .col-sm-3
    %h3.general-subtitle Billing Address
    %p.general-address
      John Doe
      %span.general-edit edit
      %br
      44 Fifth Ave v231
      %br
      New York NY 1001
      %br
      United States
      %br
      Phone +16507599755
  .col-sm-3
    %h3.general-subtitle Shipments
    %p.general-address
      Delivery Next Day!
      %span.general-edit edit
      %br
      By train
  .col-sm-3
    %h3.general-subtitle Payment Information
    %p.general-address
      ** ** ** 8756
      %span.general-edit edit
      %br
      12/2018
.visible-xs
  .general-cart-item.divider-lg
    .general-img-wrap-table
      %img.cart-img-shadow.width-full{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
    %p.general-title Android Programming for Beginners
    %P.in-grey-600.font-weight-light A recipe-based book to help you efficiently create amazing PHP-based applications with Laravel 5.x
    %table.table
      %tr
        %td
          %span.in-grey-600 Price
        %td
          %span.font-16.in-gold-500 €28.50
      %tr
        %td.vertical-middle
          %span.in-grey-600 Quantity
        %td
          %span 1
      %tr
        %td
          %span.in-grey-600 SubTotal
        %td
          %span.font-16.in-gold-500 €32.90
  .general-cart-item.divider-lg.mb-55
    .general-img-wrap-table
      %img.cart-img-shadow.width-full{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
    %p.general-title Android Programming for Beginners
    %table.table
      %tr
        %td
          %span.in-grey-600 Price
        %td
          %span.font-16.in-gold-500 €28.50
      %tr
        %td.vertical-middle
          %span.in-grey-600 Quantity
        %td
          .input-group
            %a.input-link{href: "#"}
              %i.fa.fa-minus.line-height-40
            %input.form-control.quantity-input{type: "text"}
            %a.input-link{href: "#"}
              %i.fa.fa-plus.line-height-40
      %tr
        %td
          %span.in-grey-600 SubTotal
        %td
          %span.font-16.in-gold-500 €32.90
.hidden-xs.divider-lg.pt-20
  %table.table.table-hover
    %thead
      %tr
        %th
          %span.in-grey-600 Book
        %th.col-method
        %th
          %span.in-grey-600 Price
        %th
          %span.in-grey-600 Quantity
        %th
          %span.in-grey-600 Total
    %tbody
      %tr
        %td
          .general-img-wrap-table
            %img.cart-img-shadow.pull-left.width-full{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
        %td
          %p.general-title Android Programming for Beginners
          %p.in-grey-600.font-weight-light Maximize the potential of Bootstrap with a collection of real-world site projects for better, faster, more responsive web applications
        %td
          %span.font-16.in-gold-500 €28.50
        %td
          %span.ml-30 1
        %td
          %span.font-16.in-gold-500 €32.90
.text-center.general-text-right
  %p.in-gold-500.font-18 Order Summary
  %table.general-summary-table.general-summary-table-right.general-text-right
    %tr
      %td
        %p.font-16 Subtotal:
      %td
        %p.font-16 €117.69
    %tr
      %td
        %p.font-16 Coupon:
      %td
        %p.font-16 €0.00
    %tr
      %td
        %strong.font-18 Order Total:
      %td
        %strong.font-18 €117.69
.text-center
  %button.btn.btn-default.mb-20 Place Order