config/routes.rb
Rails.application.routes.draw do

  get 'settings/index'

  get 'settings/update'

  get 'view_orders/index'

  get '/en/home_index_path' => 'home#index'
  
  get '/en/cart_path' => 'carts#show'

  get '/en/product/category/:id', to: 'products#category', as: 'category' 

  get '/en/carts/:id/cupon_path', to: 'carts#cupon_apply', as: 'cupon'
  
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  scope '(:locale)' do
    resources :settings, only: [:index, :create, :destroy]
    resource :settings, only: [:edit] do
      collection do
        patch 'update_password'
      end
    end
    resources :home, only: [:index, :create]
    resources :books, only: [:show, :update]
    resources :orders, only: [:index, :create]
    resources :line_items, only: [:index, :new, :create, :update, :destroy]
    resources :carts, only: [:show, :edit]
    resources :payment, only: [:index, :create]
    resources :confirm, only: [:index]
    resources :complete, only: [:index]
    resources :delivery, only: [:index, :create]
    resources :view_orders, only: [:index]
    resource :product do
      resources :comments
    end

    root 'home#index', as: 'store', via: :all
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product_id, quantity = '1')
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += quantity.to_i
    else
      current_item = line_items.build(product_id: product_id)
      current_item.quantity = quantity.to_i
    end
    current_item
  end

  def del_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    unless current_item.nil?
      if current_item.quantity > 1
        current_item.quantity -= 1
      else
        current_item.destroy
      end
    end
    current_item
  end

  def destroy_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    current_item.destroy
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

  def total_cupon
    @cupon = Cupon.find(self.cupon_id)
    @cupon.price
  end
end
 

app/controllers/carts_controller.rb
class CartsController < InheritedResources::Base
  
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  def show
    @cupon ||= Cupon.new(price: 0, id: 1)
    @cart.cupon_id = 1
    @cart.save
  end

  def edit
    @cupon = Cupon.find(params[:id])
    render action: 'show'
  end

  def cupon_apply
    @number = params[:cupon]
    @cupon = Cupon.where(number: @number[:number]).first
    @cupon ||= Cupon.new(price: 0, id: 1)
    @cart.cupon_id = @cupon.id
    @cart.save
    render action: 'show'
  end

  private

  def invalid_cart
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to store_url, notice: 'Invalid cart'
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.haml
%h1.general-title-margin= t('.cart')
.hidden-xs
  %table.table.table-hover
    %tr.no-hover
      %th.col-pic.pl-0
        %span.in-grey-600= t('.product')
      %th.col-title
      %th.col-price
        %span.in-grey-600= t('.price')
      %th.col-quantity
        %span.in-grey-600= t('.quantity')
      %th.col-total
        %span.in-grey-600= t('.subtotal')
      %th.col-close
    - @cart.line_items.each do |item|
      %tr
        %td
          .general-img-wrap-table
            %img.cart-img-shadow.pull-left.width-full{src: item.product.image_url}
        %td
          %p.general-title= item.product.title
        %td
          %span.font-16.in-gold-500= "€#{item.product.price}"
        %td
          .input-group
            = link_to '', line_item_path(product_id: item.product.id), method: :patch, class: "input-link fa fa-minus line-height-40"
            %input.form-control.quantity-input{:type => "text", :value => item.quantity}
            = link_to '', line_items_path(product_id: item.product.id), remote: true, method: :post, class: "input-link fa fa-plus line-height-40"
        %td
          %span.font-16.in-gold-500= number_to_currency(item.total_price)
        %td
          = button_to 'x',  line_item_path(product_id: item.product.id), method: :delete, class: 'close general-cart-close'
.general-order-wrap
  .row
    .col-sm-4
      = form_for @cupon, url: cupon_path, method: :get do |f|
        = f.label :number, t('.enter_your_coupon_code'), { class: 'font-weight-light', for: "number" }
        = f.text_field :number, { class: 'form-control mb-30', type: "text", placeholder: "Enter Your Coupon Code" }
        = f.submit 'Update Cart', {class: 'btn btn-primary mb-15 res-block'}
    .col-sm-8
      .res-mr-200.text-center.general-text-right
        %p.in-gold-500.font-18= t('.order_summary')
        %table.general-summary-table.general-summary-table-right.general-text-right
          %tr
            %td
              %p.font-16= t('.subtotal')
            %td
              %p.font-16= number_to_currency(@cart.total_price)
          %tr
            %td
              %p.font-16= t('.coupon')
            %td
              %p.font-16= number_to_currency(@cupon.price)
          %tr
            %td
              %strong.font-18= t('.order_total')
            %td
              %strong.font-18= number_to_currency(@cart.total_price - @cupon.price)
        %button.btn.btn-default.mb-20.visible-xs-inline-block= t('.checkout')
= button_to "Checkout", orders_path, method: :get, class: 'btn btn-default mb-20 hidden-xs center-block' 