config/routes.rb
Rails.application.routes.draw do

  get 'settings/index'

  get 'settings/update'

  get 'view_orders/index'

  get '/en/home_index_path' => 'home#index'
  
  get '/en/cart_path' => 'carts#show'

  get '/en/product/category/:id', to: 'products#category', as: 'category' 

  get '/en/carts/:id/cupon_path', to: 'carts#cupon_apply', as: 'cupon'
  
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  scope '(:locale)' do
    resources :settings, only: [:index, :create, :destroy]
    resource :settings, only: [:edit] do
      collection do
        patch 'update_password'
      end
    end
    resources :home, only: [:index, :create]
    resources :books, only: [:show, :update]
    resources :orders, only: [:index, :create]
    resources :line_items, only: [:index, :new, :create, :update, :destroy]
    resources :carts, only: [:show, :edit]
    resources :payment, only: [:index, :create]
    resources :confirm, only: [:index]
    resources :complete, only: [:index]
    resources :delivery, only: [:index, :create]
    resources :view_orders, only: [:index]
    resource :product do
      resources :comments
    end

    root 'home#index', as: 'store', via: :all
  end
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :comments, dependent: :destroy
  has_many :line_items
  has_many :orders, through: :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  belongs_to :author
  belongs_to :category

  mount_uploader :image_url, PictureUploader

  def self.latest
    Product.order(:updated_at).last
  end
	
  private
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'There are headings')
      return false
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def show
    view_param_sort
    @catego = Array.new
    Category.all.each {|c| @catego << c.id}
    session[:category] ||= @catego
    @product = Product.order(sort_column + ' ' + sort_direction).where(category_id: session[:category]).page(params[:page]).per(8)
    @categories = Category.all
  end

  def category
    view_param_sort
    if params[:id] == 'all'
      @catego = Array.new
      Category.all.each {|c| @catego << c.id}
      session[:category] = @catego
      @product = Product.order(sort_column + ' ' + sort_direction).where(category_id: session[:category]).page(params[:page]).per(8)
    else
      session[:category] = params[:id]
      @product = Product.where(category_id: params[:id]).page(params[:page]).per(8)
    end
    @categories = Category.all
    render 'show' 
  end

  private

  def sort_column
    Product.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "desc"
  end

  def view_param_sort
    if params[:name_sort].nil?
      @name_sort = 'Newest first'
    else
      @name_sort = params[:name_sort]
    end
  end
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/products/show.html.haml
%h1.general-title-margin Сatalog
.hidden-xs.clearfix
  .pull-right
    .dropdown
      %a.dropdown-toggle.dropdown-btn.width-240{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}
        = @name_sort
        %i.fa.fa-angle-down.dropdown-icon
      %ul.dropdown-menu
        %li
          = link_to 'Newest first', product_path(:sort => "created_at", :direction => "desc", :name_sort => "Newest first"), method: "get"
        %li
          = link_to 'Popular first', product_path(:sort => "views", :direction => "desc", :name_sort => "Popular first"), method: "get"
        %li
          = link_to 'Price: Low to high', product_path(:sort => "price", :direction => "asc", :name_sort => "Price: Low to high"), method: "get"
        %li
          = link_to 'Price: High to low', product_path(:sort => "price", :direction => "desc", :name_sort => "Price: high to low"), method: "get"
        %li
          = link_to 'Title A-Z', product_path(:sort => "title", :direction => "asc", :name_sort => "Title A-Z"), method: "get"
        %li
          = link_to 'Title Z-A', product_path(:sort => "title", :direction => "desc", :name_sort => "Title Z-A"), method: "get"
  %ul.list-inline.pt-10.mb-25.mr-240
    %li.mr-35
      %a.filter-link{href: "#{category_path('all')}"}
        All
        %span.badge.general-badge= Product.all.size
    - @categories.each do |category|
      %li.mr-35
        %a.filter-link{href: "#{category_path(category.id)}"}
          = category.category
          %span.badge.general-badge= Product.where(category_id: category.id).size
.mb-40.visible-xs
  %p.in-grey-600.small.mb-10 Filter by category
  .dropdown.mb-20
    %a.dropdown-toggle.dropdown-btn.width-100{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}
      Newest first
      %i.fa.fa-angle-down.dropdown-icon
    %ul.dropdown-menu
      %li
        %a{href: "#"} Newest first
      %li
        %a{href: "#"} Popular first
      %li
        %a{href: "#"} Price: Low to hight
      %li
        %a{href: "#"} Price: Low to hight
  %p.in-grey-600.small.mb-10 Sort by
  .dropdown
    %a.dropdown-toggle.dropdown-btn.width-100{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}
      Newest first
      %i.fa.fa-angle-down.dropdown-icon
    %ul.dropdown-menu
      %li
        %a{href: "#"} Newest first
      %li
        %a{href: "#"} Popular first
      %li
        %a{href: "#"} Price: Low to hight
      %li
        %a{href: "#"} Price: Low to hight`
.mb-120
  .row
    - paginate @product
    - @product.each_slice(4) do |row_product|
      .row.mb-25
        - row_product.each do |product|
          .col-xs-6.col-sm-3
            .general-thumb-wrap
              .thumbnail.general-thumbnail
                %img.img-shadow.general-thumbnail-img{src: product.image_url, alt: "design-book"}
                .thumb-hover
                  .general-thumb-link-wrap
                    %a.thumb-hover-link{href: "#{book_path(id: product)}"}
                      %i.fa.fa-eye.thumb-icon{'aria-hidden': "true"}
                    %a.thumb-hover-link{href: "#{line_items_path(product_id: product)}"}
                      %i.fa.fa-shopping-cart.thumb-icon
            .general-thumb-info
              %p.general-title= product.title
              %p.font-16.in-gold-500= number_to_currency(product.price)
              %span.divider-sm
              %p.in-grey-600.small= "#{product.author.first_name} #{product.author.last_name}"
  .text-center
    = link_to_prev_page @product, 'Prev Page', class: 'btn btn-primary'
    = link_to_next_page @product, 'Next Page', class: 'btn btn-primary'